-- ============================================================
-- MIGRATION — Multi-utilisateur (auth + cloisonnement par user_id)
-- À exécuter dans Supabase → SQL Editor → Run.
-- Idempotente : inclut aussi profil + rpe (si pas déjà fait) et peut être relancée.
-- ============================================================

-- 0) Prérequis des migrations précédentes (sans effet si déjà présents)
alter table sessions add column if not exists rpe integer check (rpe between 1 and 10);

create table if not exists profile (
  id                bigint generated by default as identity primary key,
  nom text, sexe text, age integer, poids_kg numeric, taille_cm numeric,
  fc_max integer, fc_repos integer, objectif text, calendrier text,
  blessures text, preferences_alim text, notes_coach text,
  updated_at timestamptz default now()
);
alter table profile drop constraint if exists profile_singleton;

-- 1) Colonne user_id sur toutes les tables + valeur par défaut = utilisateur connecté
alter table sessions  add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table nutrition add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table sleep     add column if not exists user_id uuid references auth.users(id) on delete cascade;
alter table profile   add column if not exists user_id uuid references auth.users(id) on delete cascade;

alter table sessions  alter column user_id set default auth.uid();
alter table nutrition alter column user_id set default auth.uid();
alter table sleep     alter column user_id set default auth.uid();
alter table profile   alter column user_id set default auth.uid();

-- Profil : clé = user_id (une ligne par utilisateur).
-- Répare aussi les anciennes installs où profile.id avait un défaut fixe (=1),
-- qui provoquait "duplicate key value violates unique constraint profile_pkey".
delete from profile where user_id is null;
alter table profile drop column if exists id cascade;
drop index if exists profile_user_id_key;
do $$ begin
  if not exists (select 1 from pg_constraint where conrelid = 'profile'::regclass and contype = 'p') then
    alter table profile add primary key (user_id);
  end if;
end $$;

-- 2) RLS : chacun ne voit et ne modifie que SES lignes
alter table sessions  enable row level security;
alter table nutrition enable row level security;
alter table sleep     enable row level security;
alter table profile   enable row level security;

drop policy if exists "allow all sessions"  on sessions;
drop policy if exists "allow all nutrition" on nutrition;
drop policy if exists "allow all sleep"     on sleep;
drop policy if exists "allow all profile"   on profile;

create policy "own sessions"  on sessions  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own nutrition" on nutrition for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own sleep"     on sleep     for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own profile"   on profile   for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ============================================================
-- 3) BACKFILL — À LANCER UNE FOIS, APRÈS avoir créé ton compte dans l'app.
--    Remplace ton@email.com par l'email de TON compte, décommente et Run.
--    (Rattache tes données existantes — 16 séances, etc. — à ton compte.)
-- ============================================================
-- update sessions  set user_id = (select id from auth.users where email = 'ton@email.com') where user_id is null;
-- update nutrition set user_id = (select id from auth.users where email = 'ton@email.com') where user_id is null;
-- update sleep     set user_id = (select id from auth.users where email = 'ton@email.com') where user_id is null;
-- update profile   set user_id = (select id from auth.users where email = 'ton@email.com') where user_id is null;
