-- ============================================================
-- MIGRATION — Photos de progression (Supabase Storage + métadonnées)
-- À exécuter dans Supabase → SQL Editor → Run. Idempotente.
-- ============================================================

-- 1) Table des métadonnées photo (le fichier vit dans Storage)
create table if not exists photos (
  id          bigint generated by default as identity primary key,
  user_id     uuid references auth.users(id) on delete cascade default auth.uid(),
  date        date not null default current_date,
  type        text not null default 'progress',   -- 'progress' | 'goal'
  path        text not null,                        -- chemin dans le bucket : {user_id}/xxx.jpg
  created_at  timestamptz default now()
);
alter table photos enable row level security;
drop policy if exists "own photos" on photos;
create policy "own photos" on photos for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 2) Bucket de stockage privé
insert into storage.buckets (id, name, public) values ('photos', 'photos', false)
on conflict (id) do nothing;

-- 3) Accès Storage : chaque utilisateur ne touche que son dossier ({user_id}/…)
drop policy if exists "photos read own"   on storage.objects;
drop policy if exists "photos insert own" on storage.objects;
drop policy if exists "photos delete own" on storage.objects;

create policy "photos read own"   on storage.objects for select
  using (bucket_id = 'photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "photos insert own" on storage.objects for insert
  with check (bucket_id = 'photos' and (storage.foldername(name))[1] = auth.uid()::text);
create policy "photos delete own" on storage.objects for delete
  using (bucket_id = 'photos' and (storage.foldername(name))[1] = auth.uid()::text);
