-- ============================================================
-- MIGRATION — Mémoire persistante des coachs IA (sport + nutrition)
-- À exécuter dans Supabase → SQL Editor → Run. Idempotente.
-- ============================================================

create table if not exists coach_messages (
  id                bigint generated by default as identity primary key,
  user_id           uuid references auth.users(id) on delete cascade default auth.uid(),
  coach_type        text not null check (coach_type in ('sport', 'nutrition')),
  role              text not null check (role in ('user', 'assistant')),
  content           text not null default '',
  image_data        text,
  image_media_type  text,
  created_at        timestamptz default now()
);

alter table coach_messages enable row level security;
drop policy if exists "own coach_messages" on coach_messages;
create policy "own coach_messages" on coach_messages for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create index if not exists coach_messages_user_type_created on coach_messages(user_id, coach_type, created_at);
