-- ============================================================
-- MIGRATION — Siestes + estimation IA "sans montre"
-- À exécuter dans Supabase → SQL Editor → Run. Idempotente.
-- ============================================================

-- 1) Table des siestes (plusieurs possibles par jour et par utilisateur)
create table if not exists naps (
  id            bigint generated by default as identity primary key,
  user_id       uuid references auth.users(id) on delete cascade default auth.uid(),
  date          date not null,
  heure_debut   text not null,
  heure_fin     text not null,
  duree_minutes integer,
  qualite       integer check (qualite between 1 and 10),
  note          text,
  created_at    timestamptz default now()
);

alter table naps enable row level security;
drop policy if exists "own naps" on naps;
create policy "own naps" on naps for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 2) Séance "sans montre" estimée par l'IA
alter table sessions add column if not exists sans_montre boolean default false;
alter table sessions add column if not exists ai_recommendation text;
