-- ============================================================
-- MIGRATION — Suivi du poids + corrections multi-utilisateur
-- À exécuter dans Supabase → SQL Editor → Run. Idempotente.
-- ============================================================

-- 1) Table des mesures corporelles (1 par jour et par utilisateur)
create table if not exists measurements (
  id                bigint generated by default as identity primary key,
  user_id           uuid references auth.users(id) on delete cascade default auth.uid(),
  date              date not null,
  poids_kg          numeric,
  tour_taille_cm    numeric,
  masse_grasse_pct  numeric,
  note              text,
  created_at        timestamptz default now(),
  unique (user_id, date)
);

alter table measurements enable row level security;
drop policy if exists "own measurements" on measurements;
create policy "own measurements" on measurements for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 2) Objectif de poids sur le profil
alter table profile add column if not exists poids_objectif numeric;

-- 3) CORRECTION multi-utilisateur : les contraintes d'unicité étaient GLOBALES
--    (date+sport, date+repas, date) → deux comptes différents entraient en
--    collision. On les remplace par des contraintes PAR UTILISATEUR.
alter table sessions  drop constraint if exists sessions_date_sport_key;
alter table nutrition drop constraint if exists nutrition_date_repas_key;
alter table sleep     drop constraint if exists sleep_date_key;

create unique index if not exists sessions_user_date_sport  on sessions(user_id, date, sport);
create unique index if not exists nutrition_user_date_repas on nutrition(user_id, date, repas);
create unique index if not exists sleep_user_date           on sleep(user_id, date);
